name: 'Setup namespace'
description: 'Check and trim namespace'

inputs:
  text:
    description: 'The text to trim'
    required: true
    type: string
  max-length:
    description: 'Maximum length before trimming'
    required: false
    default: 40
    type: string

outputs:
  text:
    description: 'The trimmed text "OUT"'

runs:
  using: 'composite'
  steps:
    - name: Trim
      shell: bash
      run: |

        echo "text = ${{ inputs.text }}"
        echo "max-length = ${{ inputs.max-length }}"

        TEXT="${{ inputs.text }}"

        OUT="${TEXT:0:${{ inputs.max-length }}}"

        echo "result = ${OUT}"

        # Set the output value for 'trimmed-text'
        # echo "::set-output name=text::${OUT}"

        echo "text=${OUT}" >> $GITHUB_OUTPUT

        echo $GITHUB_OUTPUT
